import * as dotenv from "dotenv";
dotenv.config();

export default {
    STATUS_CODES: {
        OK: 200,
        CREATED: 201,
        BAD_REQUEST: 400,
        UNAUTHORIZED: 401,
        FORBIDDEN: 403,
        NOT_FOUND: 404,
        INTERNAL_SERVER_ERROR: 500,
        CONFLICT: 409,
        NO_CONTENT: 204,
    },
    MESSAGES: {
        BAD_REQUEST: "Bad Request",
        INTERNAL_SERVER_ERROR: "Internal server error",
        UNAUTHORIZED: "Unauthorized",
        FORBIDDEN: "Forbidden",
        PERMISSION_DENIED: "Permission denied!",
        SOMETHING_WENT_WRONG: "Something went wrong",
        INVALID_TOKEN: "Invalid token",
        TOKEN_EXPIRED: "This token has been expired",
        LAT_LONG_REQUIRED: "Latitude and Longitude are required",
        FILTER_IS_REQUIRED: "Filter is required",
        INVALID_ID: "Invalid ID",
        ALREADY_EXISTS: "ALREADY EXISTS",
        DOES_NOT_EXISTS: "DOES NOT EXISTS",
        CREATED_SUCCESSFULLY: "ADDED SUCCESSFULLY",
        UPDATED_SUCCESSFULLY: "UPDATED SUCCESSFULLY",
        SELECT_AT_LEAST_ONE: "SELECT AT LEAST ONE",
        DELETED_SUCCESSFULLY: "DELETED SUCCESSFULLY",
        IMPORTED_SUCCESSFULLY: "IMPORTED SUCCESSFULLY",
        EXPORTED_SUCCESSFULLY: "EXPORTED SUCCESSFULLY",
        NOT_FOUND: "NOT FOUND",
        USER: {
            LANG_PREF_UPDATED_SUCCESSFULLY: "Lang Pref Updated Successfully",
            EMAIL_IS_REQUIRED: "Email is required",
            REQUEST_USER_NOT_FOUND: "Request user not found",
            USER_NOT_FOUND: "User not found",
            PASSWORD_NOT_MATCH: "Password not matched",
            INVALID_PASSWORD: "Invalid password",
            YOU_CAN_NOT_USE_THIS_EMAIL: "You cannot use this email",
            USER_EXIST: "User already exist",
            USER_EXIST_WITH_EMAIL: "User already exists with this email",
            USER_EXIST_WITH_EMAIL_AND_INACTIVATED:
                "User already exists with this email and it's inactivated",
            ESTIMATOR_NOT_FOUND: "Estimator not found",
            FIELD_WORKER_NOT_FOUND: "Field Worker not found",
            PUNCH_NOT_FOUND: "Punch not found",
            CLOCK_IN_NOT_FOUND: "Clock in not found",
            ALREADY_CLOCKED_IN: "Already clocked in",
            ALREADY_CLOCKED_OUT: "Already clocked out",
            REIMBURSED_USER_NOT_FOUND: "Reimbursed user not found",
            EMAIL_NOT_VERIFIED: "Email is not verified",
            EMAIL_ALREADY_VERIFIED: "Email is already verified",
            INVALID_OTP: "Invalid OTP",
        },
    },
    AUTHENTICATION: {
        APP_SECRET: String(process.env.APP_SECRET),
    },
    SHOPIFY_DOMAIN: String(process.env.SHOPIFY_DOMAIN),
    STOREFRONT_API_VERSION: String(process.env.STOREFRONT_API_VERSION),
    STOREFRONT_TOKEN: String(process.env.STOREFRONT_TOKEN),
    JWT_SECRET: String(process.env.JWT_SECRET),
    ADMIN_API_ACCESS_TOKEN: String(process.env.ADMIN_API_ACCESS_TOKEN),
    FORGOT_PASSWORD_LINK: String(process.env.FORGOT_PASSWORD_LINK),
};
